#!/usr/bin/env python3

import json

test_data = {
    "age": "1",
    "latitude": "39.521299",
    "longitude": "-79.756219",
    "elevation": "40.4",
    "course": "274.1",
    "speed": "0.0"
}

print(json.dumps(test_data))
